---
exo:
  ingestion:
    dataset:
      autobuses:
        - name: 4 Autobus - Secteur Sorel-Varennes
          url: https://exo.quebec/xdata/citsv/google_transit.zip
          type: zip
          output_path: resources/autobus_secteur_sainte_julie.csv
      trains:
        - name: 1 Lignes de train exo
          url: https://exo.quebec/donnees_geomatiques/train_lignes_exo.geojson
          type: geojson